let beasts = [
  {
    id: 0,
    name: "Cyclops",
    habitat: "Greek islands",
    dangerRating: 3,
    description: "A one-eyed giant",
    encounterRate: 0.05,
    loot: ["a giant eye", "sheep", "blood"],
  },
  {
    id: 1,
    name: "Siren",
    habitat: "The sea",
    dangerRating: 5,
    description: "Really good looking but slightly psychotic",
    encounterRate: 0.5,
    loot: ["a haunting melody", "sailors' bones"],
  },
  {
    id: 2,
    name: "Minotaur",
    habitat: "Greek labyrinth",
    dangerRating: 4,
    description: "Half-man, half-bull",
    encounterRate: 0.3,
    loot: ["six pack", "horns", "thread"],
  },
  {
    id: 3,
    name: "Loch Ness Monster",
    habitat: "Scottish highlands",
    dangerRating: 1,
    description: "A mystical long-necked lady",
    encounterRate: 0.001,
    loot: ["teeth", "camera"],
  },
  {
    id: 4,
    name: "Bogeyman",
    habitat: "In the sewers",
    dangerRating: 3,
    description: "A creepy man scaring the children",
    encounterRate: 0.1,
    loot: ["thumbs", "a party bag", "red nose"],
  },
  {
    id: 5,
    name: "Centaurs",
    habitat: "Greek forests",
    dangerRating: 2,
    description: "Half-man, full horse",
    encounterRate: 0.3,
    loot: ["horse shoe", "clump of hair"],
  },
  {
    id: 6,
    name: "Gnomes",
    habitat: "Front gardens during Christmas",
    dangerRating: 5,
    description: "Small pointy guard of the homes",
    encounterRate: 0.7,
    loot: ["big hat", "stolen amazon deliveries", "soil"],
  },
  {
    id: 7,
    name: "Leprechaun",
    habitat: "At the end of a rainbow",
    dangerRating: 1,
    description: "A luck-bearing shoemaker",
    encounterRate: 0.005,
    loot: ["chocolate gold coins", "shamrock", "glitter"],
  },
  {
    id: 8,
    name: "Faeries",
    habitat: "On dark leaves",
    dangerRating: 2,
    description: "Small, flying beings",
    encounterRate: 0.2,
    loot: ["mini broomstick", "love potion"],
  },
  {
    id: 9,
    name: "Bigfoot",
    habitat: "Alaska",
    dangerRating: 3,
    description: "An elusive giant",
    encounterRate: 0.01,
    loot: ["size 20 shoe", "long nail"],
  },
];

module.exports = beasts;
